name: Cloud CI Pipeline

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Print Python Version
        run: python --version

      - name: Run Application
        run: python app.py

      - name: Run Tests
        run: python test_app.py

      - name: Echo Build Message
        run: echo "CI Pipeline executed successfully!"